/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_nanodetncnn_JavaCallC */

#ifndef _Included_com_tencent_nanodetncnn_JavaCallC
#define _Included_com_tencent_nanodetncnn_JavaCallC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_nanodetncnn_JavaCallC
 * Method:    varifyCheck
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_tencent_nanodetncnn_JavaCallC_varifyCheck
  (JNIEnv *, jobject, jchar);

#ifdef __cplusplus
}
#endif
#endif
